import type { ClubMatch, MatchCallup, Player, TrainingSession, VolleyballEvent } from "./types";

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

function dateOffsetIso(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const seedPlayers: Player[] = [
  {
    id: "p-1",
    name: "Ramsey",
    number: "7",
    aliases: ["ramsey"],
    position: "Outside Hitter",
    category: "U-18",
    status: "active",
    phone: "+56 9 5555 0001",
    guardianName: "Caroline Ramsey",
    guardianPhone: "+56 9 1111 1111",
  },
  {
    id: "p-2",
    name: "Sutton",
    number: "12",
    aliases: ["sutton"],
    position: "Opposite",
    category: "U-18",
    status: "active",
    guardianName: "Patricia Sutton",
    guardianPhone: "+56 9 1111 2222",
  },
  {
    id: "p-3",
    name: "Martin",
    number: "4",
    aliases: ["martin"],
    position: "Middle Blocker",
    category: "U-18",
    status: "active",
    guardianName: "Andrea Martin",
    guardianPhone: "+56 9 1111 3333",
  },
  {
    id: "p-4",
    name: "Vance",
    number: "9",
    aliases: ["vance"],
    position: "Setter",
    category: "Adult",
    status: "active",
    phone: "+56 9 5555 0004",
  },
  {
    id: "p-5",
    name: "Nelson",
    number: "2",
    aliases: ["nelson"],
    position: "Libero",
    category: "Adult",
    status: "active",
    phone: "+56 9 5555 0005",
  },
  {
    id: "p-6",
    name: "Carter",
    number: "5",
    aliases: ["carter"],
    position: "Outside Hitter",
    category: "Adult",
    status: "injured",
    phone: "+56 9 5555 0006",
    notes: "Right ankle",
  },
  {
    id: "p-7",
    name: "Bryce",
    number: "8",
    aliases: ["bryce"],
    position: "Middle Blocker",
    category: "U-18",
    status: "active",
    guardianName: "Felix Bryce",
    guardianPhone: "+56 9 1111 4444",
  },
  {
    id: "p-8",
    name: "Lawson",
    number: "10",
    aliases: ["lawson"],
    position: "Opposite",
    category: "Adult",
    status: "active",
    phone: "+56 9 5555 0008",
  },
];

export const seedMatches: ClubMatch[] = [
  {
    id: "m-1",
    date: dateOffsetIso(2),
    time: "19:30",
    opponent: "Condors",
    location: "Municipal Gym",
    competition: "Regional League",
    status: "scheduled",
  },
  {
    id: "m-2",
    date: dateOffsetIso(7),
    time: "20:00",
    opponent: "Southern Tigers",
    location: "Central Sports Complex",
    competition: "Regional League",
    status: "scheduled",
  },
  {
    id: "m-3",
    date: todayIso(),
    time: "18:00",
    opponent: "Falcons",
    location: "Club Court",
    competition: "Friendly",
    status: "live",
  },
  {
    id: "m-4",
    date: dateOffsetIso(-5),
    time: "19:00",
    opponent: "Pumas",
    location: "North Gym",
    competition: "Regional League",
    status: "finished",
    notes: "Win 3-1",
  },
];

export const seedCallups: MatchCallup[] = [
  {
    matchId: "m-1",
    availability: {
      "p-1": "available",
      "p-2": "available",
      "p-3": "maybe",
      "p-4": "available",
      "p-5": "pending",
      "p-7": "available",
      "p-8": "unavailable",
    },
  },
  {
    matchId: "m-2",
    availability: {
      "p-1": "pending",
      "p-2": "pending",
      "p-4": "available",
      "p-5": "pending",
      "p-7": "pending",
    },
  },
  {
    matchId: "m-3",
    availability: {
      "p-1": "available",
      "p-2": "available",
      "p-3": "available",
      "p-4": "available",
      "p-5": "available",
      "p-7": "available",
    },
  },
  {
    matchId: "m-4",
    availability: {},
  },
];

export const seedTrainingSessions: TrainingSession[] = [
  {
    id: "t-1",
    date: todayIso(),
    time: "18:00",
    focus: "Serve and reception",
    location: "Court 1",
    loads: {
      "p-1": { present: true, minutes: 90, rpe: 6, fatigue: 3, pain: 0 },
      "p-2": { present: true, minutes: 75, rpe: 7, fatigue: 4, pain: 1 },
      "p-3": { present: false, minutes: 0, rpe: 0, fatigue: 0, pain: 0, notes: "Absent" },
      "p-4": { present: true, minutes: 90, rpe: 5, fatigue: 3, pain: 0 },
      "p-5": { present: true, minutes: 90, rpe: 6, fatigue: 2, pain: 0 },
      "p-7": { present: true, minutes: 80, rpe: 7, fatigue: 4, pain: 1 },
      "p-8": { present: true, minutes: 90, rpe: 8, fatigue: 5, pain: 2 },
    },
  },
  {
    id: "t-2",
    date: dateOffsetIso(-2),
    time: "18:00",
    focus: "Attack and block",
    location: "Court 1",
    loads: {
      "p-1": { present: true, minutes: 100, rpe: 7, fatigue: 4, pain: 0 },
      "p-2": { present: true, minutes: 100, rpe: 8, fatigue: 5, pain: 0 },
      "p-3": { present: true, minutes: 90, rpe: 6, fatigue: 3, pain: 0 },
      "p-4": { present: true, minutes: 100, rpe: 6, fatigue: 4, pain: 0 },
      "p-5": { present: true, minutes: 100, rpe: 7, fatigue: 4, pain: 1 },
    },
  },
];

export const seedEvents: VolleyballEvent[] = [
  {
    id: "e-1",
    sequence: 1,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramsey",
    actionType: "serve",
    result: "ace",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-2",
    sequence: 2,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-2",
    playerName: "Sutton",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-3",
    sequence: 3,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-3",
    playerName: "Martin",
    actionType: "block",
    result: "stuff",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-4",
    sequence: 4,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-4",
    playerName: "Vance",
    actionType: "set",
    result: "positive",
    source: "manual",
  },
  {
    id: "e-5",
    sequence: 5,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-5",
    playerName: "Nelson",
    actionType: "dig",
    result: "perfect",
    source: "manual",
  },
  {
    id: "e-6",
    sequence: 6,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramsey",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-7",
    sequence: 7,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-2",
    playerName: "Sutton",
    actionType: "serve",
    result: "ace",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-8",
    sequence: 8,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-7",
    playerName: "Bryce",
    actionType: "block",
    result: "stuff",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-9",
    sequence: 9,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramsey",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-10",
    sequence: 10,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-3",
    playerName: "Martin",
    actionType: "attack",
    result: "error",
    pointFor: "away",
    source: "manual",
  },
  {
    id: "e-11",
    sequence: 11,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-2",
    playerName: "Sutton",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-12",
    sequence: 12,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-4",
    playerName: "Vance",
    actionType: "assist",
    result: "positive",
    source: "manual",
  },
  {
    id: "e-13",
    sequence: 13,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramsey",
    actionType: "serve",
    result: "in_play",
    source: "manual",
  },
  {
    id: "e-14",
    sequence: 14,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-7",
    playerName: "Bryce",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-15",
    sequence: 15,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-5",
    playerName: "Nelson",
    actionType: "dig",
    result: "perfect",
    source: "manual",
  },
  {
    id: "e-16",
    sequence: 16,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramsey",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
];

export const seedClubName = "Sporti Volley Club";
